apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  namespace: edu-olga-vinokurova
spec:
  schedule: "0 2 * * *"
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: clearsessions
              image: olgavino25/django-site:6e4ee00
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: dsn
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secrets
                      key: SECRET_KEY
              volumeMounts:
                - name: ssl-certs
                  mountPath: /root/.postgresql
                  readOnly: true
          volumes:
            - name: ssl-certs
              secret:
                secretName: postgres
                items:
                  - key: root.crt
                    path: root.crt
                    mode: 0600
